music/urls.py
from django.conf.urls import url
from . import views
app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^viewall/$', views.viewall, name='viewall'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<playlist_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
    url(r'^add_playlist/$', views.add_playlist, name='add_playlist'),
    url(r'^(?P<playlist_id>[0-9]+)/add_song/$', views.add_song, name='add_song'),
    url(r'^(?P<playlist_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
    url(r'^(?P<playlist_id>[0-9]+)/favorite_playlist/$', views.favorite_playlist, name='favorite_playlist'),
    url(r'^(?P<playlist_id>[0-9]+)/delete_playlist/$', views.delete_playlist, name='delete_playlist'),
    url(r'^newsfeed/$', views.newsfeed, name='newsfeed')
]

   
    

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/',include('music.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.views.generic import RedirectView
urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/music/', permanent=True)), #crucial
]

music/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
# Create your models here.

class Playlist(models.Model):

    user = models.ForeignKey(User, default=1)
    title = models.CharField(max_length=500)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Song(models.Model):

    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField(default='')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Playlist, Song

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['song_title','audio_file']


class PlaylistForm(forms.ModelForm):

    class Meta:
        model = Playlist
        fields = ['title']

music/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import logout
from django.http import JsonResponse
from django.db.models import Q
from .models import Playlist, Song
from .forms import PlaylistForm, SongForm, UserForm

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

def index(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        playlists = Playlist.objects.filter(user=request.user)
        song_results = Song.objects.all()
        query = request.GET.get("q")
        if query:
            playlists = playlists.filter(
                Q(title__icontains=query) 
                ).distinct()
            song_results = song_results.filter(
                Q(song_title__icontains=query)
            ).distinct()
            return render(request, 'music/index.html', {
                'playlists': playlists,
                'songs': song_results,
            })
        else:
            return render(request, 'music/index.html', {'playlists': playlists}, {'songs': song_results})


def login_user(request):

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
          if user.is_active:
              login(request, user)
              playlists = Playlist.objects.filter(user=request.user)
              return render(request,'music/index.html',{'playlists': playlists})
          else:
              return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})
    return render(request, 'music/login.html')

def viewall(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        song_results = Song.objects.all()
        return render(request, 'music/viewall.html', {
            'songs': song_results,
        })
        
def detail(request, playlist_id):

    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        user = request.user
        playlist = get_object_or_404(Playlist, pk=playlist_id)
        return render(request, 'music/detail.html', {'playlist': playlist, 'user': user})


def favorite(request, song_id):

    song = get_object_or_404(Song, pk=song_id)
    try:
        if song.is_favorite:
            song.is_favorite = False
        else:
            song.is_favorite = True
        song.save()
    except (KeyError, Song.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def favorite_playlist(request, playlist_id):

    playlist = get_object_or_404(Playlist, pk=playlist_id)
    try:
        if playlist.is_favorite:
            playlist.is_favorite = False
        else:
            playlist.is_favorite = True
        playlist.save()
    except (KeyError, Playlist.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def songs(request, filter_by):

    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        try:
            song_ids = []
            for playlist in Playlist.objects.filter(user=request.user):
                for song in playlist.song_set.all():
                    song_ids.append(song.pk)
            users_songs = Song.objects.filter(pk__in=song_ids)
            if filter_by == 'favorites':
                users_songs = users_songs.filter(is_favorite=True)
        except Playlist.DoesNotExist:
            users_songs = []
        return render(request, 'music/songs.html', {
            'song_list': users_songs,
            'filter_by': filter_by,
        })


def logout_user(request):

    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'music/login.html', context)


def register(request):

    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                playlists = Playlist.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'playlists': playlists})
    context = {
        "form": form,
    }
    return render(request, 'music/register.html', context)


def add_playlist(request):

    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        form = PlaylistForm(request.POST or None)
        if form.is_valid():
            playlist = form.save(commit=False)
            playlist.user = request.user
            playlist.save()
            return render(request,'music/detail.html',{'playlist': playlist})
        context = {
            "form": form
        }
        return render(request, 'music/add_playlist.html', context)


def add_song(request, playlist_id):

    form = SongForm(request.POST or None, request.FILES or None)
    playlist = get_object_or_404(Playlist, pk=playlist_id)
    if form.is_valid():
        playlists_songs = playlist.song_set.all()
        for s in playlists_songs:
            if s.song_title == form.cleaned_data.get("song_title"):
                context = {
                    'playlist': playlist,
                    'form': form,
                    'error_message': 'You already added that song',
                }
                return render(request, 'music/add_song.html', context)
        song = form.save(commit=False)
        song.playlist = playlist
        song.audio_file = request.FILES['audio_file']
        file_type = song.audio_file.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in AUDIO_FILE_TYPES:
            context = {
                'playlist': playlist,
                'form': form,
                'error_message': 'Audio file must be WAV, MP3, or OGG',
            }
            return render(request, 'music/add_song.html', context)

        song.save()
        return render(request, 'music/detail.html', {'playlist': playlist})
    context = {
        'playlist': playlist,
        'form': form,
    }
    return render(request, 'music/add_song.html', context)


def delete_playlist(request, playlist_id):

    playlist = Playlist.objects.get(pk=playlist_id)
    playlist.delete()
    playlists = Playlist.objects.filter(user=request.user)
    return render(request, 'music/index.html', {'playlists': playlists})


def delete_song(request, playlist_id, song_id):

    playlist = get_object_or_404(Playlist, pk=playlist_id)
    song = Song.objects.get(pk=song_id)
    song.delete()
    return render(request, 'music/detail.html', {'playlist': playlist})


def newsfeed(request): #Execution of syndcation
    return render(request,"music/rss.html",{})

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Music Overloaded{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Music Overload</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block playlists_active %}{% endblock %}"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Playlists</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'music:songs' 'all' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Personal Songs</a></li>
	    <li class="{% block team %}{% endblock %}"><a href="#" target="_blank"><span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp; Team</a></li>
            </ul>
            <form class="navbar-form navbar-left" style="background-color:white;" role="search" method="get" action="{% url 'music:index' %}">
                <div class="form-group"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp;
                    <input type="text" placeholder="Search" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="{% block all %}{% endblock %}"><a href="{% url 'music:viewall' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; All Songs</a></li>
		<ul class="nav navbar-nav navbar-right">
                <li class="{% block rss %}{% endblock %}"><a href="{% url 'music:newsfeed' %}"><span class="glyphicon glyphicon-rss" aria-hidden="true"></span>&nbsp; RSS</a></li>
                <li>
                    <a href="{% url 'music:add_playlist' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Playlist
                    </a>
                </li>
                <li>
                    <a href="{% url 'music:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/base_navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Music Overloaded{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Music Overloaded</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'music:login_user' %}">Log In</a></li>
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'music:register' %}">Register</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Music Overloaded{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Music Overloaded</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'music:login_user' %}">Log In</a></li>
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'music:register' %}">Register</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/navbar.html' %}
{% block title %}{{ playlist }}{% endblock %}
{% block playlists_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        
        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'music:add_song' playlist.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Playlist</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in playlist.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>{{ song.album.title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'music:delete_song' playlist.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/index.html
{% extends 'music/navbar.html' %}
{% block playlists_active %}active{% endblock %}

{% block body %}
<div class="playlists-container container-fluid">

    <!-- Playlists -->
    <div class="row">
        <div class="col-sm-12">
            <h3 id="user-name">{{ user.username }}'s Playlists</h3>
        </div>
        {% if playlists %}
            {% for playlist in playlists %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        
                            <p>{{ playlist.title }}</p>
                            <!-- View Details -->
                            <a href="{% url 'music:detail' playlist.id %}" class="btn btn-primary btn-sm" role="button">View Songs</a>

                            <!-- Delete Playlist -->
                            <form action="{% url 'music:delete_playlist' playlist.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="playlist_id" value="{{ playlist.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Playlist -->
                            <a href="{% url 'music:favorite_playlist' playlist.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if playlist.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:add_playlist' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Playlist
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Audio File</th>
                                    <th>Playlist</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:detail' song.playlist.id %}">
                                                <img src="{{ song.playlist.playlist_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'music:detail' song.playlist.id %}">{{ song.playlist.title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if playlist.is_favorite %}active{% endif %}" style="a:active { background-color: blue; }"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

music/templates/music/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Music Overloaded{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'music/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Music Overload</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block playlists_active %}{% endblock %}"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Playlists</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'music:songs' 'all' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Personal Songs</a></li>
	    <li class="{% block team %}{% endblock %}"><a href="http://rakshit.ml" target="_blank"><span class="glyphicon glyphicon-education" aria-hidden="true"></span>&nbsp; Team</a></li>
            </ul>
            <form class="navbar-form navbar-left" style="background-color:white;" role="search" method="get" action="{% url 'music:index' %}">
                <div class="form-group"><span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp;
                    <input type="text" placeholder="Search" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="{% block all %}{% endblock %}"><a href="{% url 'music:viewall' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; All Songs</a></li>
		<ul class="nav navbar-nav navbar-right">
                <li class="{% block rss %}{% endblock %}"><a href="{% url 'music:newsfeed' %}"><i class="glyphicon glyphicon-globe"></i> RSS</a></li>
                <li>
                    <a href="{% url 'music:add_playlist' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Playlist
                    </a>
                </li>
                <li>
                    <a href="{% url 'music:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/songs.html
{% extends 'music/base.html' %}
{% block title %}All Songs{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'music:viewall' %}">View All</a></li>
                <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a href="{% url 'music:songs' 'favorites' %}">Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Audio File</th>
                                <th>Playlist</th>
                                <th>Favorite</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in song_list %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>
                                        <a target="_blank" href="{{ song.audio_file.url }}">
                                            <button type="button" class="btn btn-success btn-xs">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:detail' song.playlist.id %}">
                                            </a>
                                        <a href="{% url 'music:detail' song.playlist.id %}">{{ song.playlist.title }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}